### ISSUE TITLE
Inconsistent JWT Secret Variable Naming

### ISSUE THREAD

**Issue by Dash10107** [techcsispit/MERN-Auth-Workouts-App#1]
The JWT secret is defined as JWT_SECRET in the .env file, but the variable used throughout the code is SECRET. This inconsistency can cause confusion.

The given convention according to the Readme.md 
![image](https://github.com/user-attachments/assets/c355e51e-78b3-4584-8e72-a718cfd23e27)

The naming convention used in code 
![image](https://github.com/user-attachments/assets/aa05c9f8-b632-4952-8330-3619616083cf)
![image](https://github.com/user-attachments/assets/9a655b5a-f43f-454b-bae7-335ddecf7d1a)

This issue can cause people to face errors while trying to login or signup on the app. 

**Action Required** 
Change all instances of SECRET to JWT_SECRET in the codebase for consistency.

**Comment by Dash10107** [comment]
I would like to work on this issue

**Comment by techcsispit** [comment]
Assigned to you!
