### ISSUE TITLE
User Unable to Add Exercise Due to Expired Token Error

### ISSUE THREAD

**Issue by Dash10107** [techcsispit/MERN-Auth-Workouts-App#4]
Problem:
Users are encountering an "Authorization token required" error while trying to add exercises to the app (as shown in the screenshot). This issue occurs because the token is not being validated correctly.

![image](https://github.com/user-attachments/assets/929019af-9c3d-4c19-8e1f-350e1d572f8f)

Cause:
The issue stems from the middleware where the code checks for "authorisation" instead of the correct spelling "authorization." As a result, the middleware fails to recognize the token and thus the user, leading to the error.

![image](https://github.com/user-attachments/assets/b3f25e02-2e1f-40e4-84ec-8f64e2c48ced)

Why It’s Important:
Without fixing this, users are unable to add their workouts or interact with the app's main functionality. This breaks the user experience and prevents further app engagement.

Proposed Solution:
Update the middleware to check for "authorization" instead of "authorisation."
Ensure token validation is functioning correctly across all routes that require user authentication.
Test thoroughly to ensure the issue is resolved.

**Comment by Dash10107** [comment]
I would like to work on this issue

**Comment by Dash10107** [comment]
This issue has been resolved in the last pull request accepted.

**Comment by techcsispit** [comment]
I think this issue can be closed then
